import { AgenticWalletError, previewX402Payment, signX402Payment } from "@/lib/server/agentic-wallet";
import { createX402Intent, getX402Intent, updateX402Intent } from "@/lib/server/x402-store";
import type { X402Intent } from "@/lib/x402-types";
import { isIP } from "node:net";

export class X402Error extends Error { constructor(message:string, public readonly code="X402_ERROR"){super(message);this.name="X402Error";} }
export function x402ErrorResponse(error:unknown):Response { const e=error instanceof X402Error?error:error instanceof AgenticWalletError?new X402Error(error.message,error.code):new X402Error(error instanceof Error?error.message:"x402 operation failed."); return Response.json({error:e.message,code:e.code},{status:e.code==="X402_EXECUTION_DISABLED"?403:400}); }
export function x402Capability(){ const hosts=(process.env.AGENTPAY_X402_ALLOWED_HOSTS||"").split(",").map(v=>v.trim().toLowerCase()).filter(Boolean); return {executionEnabled:process.env.AGENTPAY_ENABLE_X402==="true",allowedHosts:hosts}; }
export function validateX402Resource(raw:string):string { let url:URL; try{url=new URL(raw);}catch{throw new X402Error("Enter a valid HTTPS x402 resource URL.","INVALID_X402_URL");} const host=url.hostname.toLowerCase(); if(url.protocol!=="https:"||url.username||url.password||url.port||host==="localhost"||host.endsWith(".local")||isIP(host)!==0) throw new X402Error("x402 resources must use an allowlisted public HTTPS hostname without credentials or custom ports.","INVALID_X402_URL"); const {allowedHosts}=x402Capability(); if(!allowedHosts.includes(host)) throw new X402Error("This x402 host is not in the server allowlist.","X402_HOST_NOT_ALLOWED"); return url.toString(); }
async function getResource(url:string, header?:{name:string;value:string}) { const controller=new AbortController(); const timer=setTimeout(()=>controller.abort(),15_000); try{return await fetch(url,{method:"GET",redirect:"error",headers:{Accept:"application/json, text/plain;q=0.9",...(header?{[header.name]:header.value}:{})},signal:controller.signal});}finally{clearTimeout(timer);} }
export async function discoverX402(rawUrl:string):Promise<X402Intent>{ const url=validateX402Resource(rawUrl); const response=await getResource(url); if(response.status!==402) throw new X402Error(`Resource returned HTTP ${response.status}, not 402 Payment Required.`,"NOT_X402_RESOURCE"); const requirements=response.headers.get("payment-required"); if(!requirements||requirements.length>65_536) throw new X402Error("The resource returned no valid PAYMENT-REQUIRED header.","MISSING_PAYMENT_REQUIREMENTS"); const preview=await previewX402Payment(requirements); if(!preview.paymentId||!Array.isArray(preview.options)) throw new X402Error("Agentic Wallet returned an invalid x402 preview.","INVALID_X402_PREVIEW"); return createX402Intent(url,preview); }
function settlementHash(value:string|null):string|undefined { if(!value)return; try{const json=JSON.parse(Buffer.from(value,"base64").toString("utf8")) as Record<string,unknown>; return typeof json.txHash==="string"?json.txHash:undefined;}catch{return;} }
export async function executeX402(id:string,index:number):Promise<X402Intent>{ if(process.env.AGENTPAY_ENABLE_X402!=="true") throw new X402Error("x402 execution is disabled on this server.","X402_EXECUTION_DISABLED"); const intent=getX402Intent(id); if(intent.status!=="awaiting-approval") throw new X402Error("This x402 intent is no longer awaiting approval.","INVALID_X402_STATUS"); if(Date.now()-Date.parse(intent.createdAt)>10*60_000) throw new X402Error("The x402 preview expired. Inspect the resource again.","X402_PREVIEW_EXPIRED"); const option=intent.options.find(o=>o.index===index); if(!option||option.status!=="READY_TO_SIGN") throw new X402Error("Select a READY_TO_SIGN payment option.","X402_OPTION_NOT_READY"); if(option.needApproveFirst) throw new X402Error("Permit2 approval payments are not enabled in this MVP.","X402_APPROVAL_REQUIRED"); updateX402Intent(id,{status:"signing",selectedIndex:index}); try{ const signature=await signX402Payment(intent.paymentId,index); if(signature.paymentHeaderName.toUpperCase()!=="PAYMENT-SIGNATURE"||!signature.paymentHeaderValue||signature.signatureExpiresAt*1000<=Date.now()) throw new X402Error("Agentic Wallet returned an invalid or expired payment signature.","INVALID_X402_SIGNATURE"); const response=await getResource(intent.resourceUrl,{name:signature.paymentHeaderName,value:signature.paymentHeaderValue}); const length=Number(response.headers.get("content-length")||0); if(length>1_000_000) throw new X402Error("Purchased response exceeds the 1 MB safety limit.","X402_RESPONSE_TOO_LARGE"); const body=(await response.text()).slice(0,64_000); if(!response.ok) return updateX402Intent(id,{status:"failed",responseStatus:response.status,responseContentType:response.headers.get("content-type")||undefined,responseBody:body,errorMessage:`Paid request returned HTTP ${response.status}.`}); return updateX402Intent(id,{status:"completed",responseStatus:response.status,responseContentType:response.headers.get("content-type")||undefined,responseBody:body,settlementTxHash:settlementHash(response.headers.get("payment-response"))}); }catch(error){updateX402Intent(id,{status:"failed",errorMessage:error instanceof Error?error.message:"x402 payment failed."});throw error;} }
