import { isIP } from "node:net";
import { AgenticWalletError,getWalletTransactionStatus,previewX402Payment,signX402Payment } from "@/lib/server/agentic-wallet";
import { createX402Intent,getX402Intent,updateX402Intent } from "@/lib/server/x402-store";
import { enforcePaymentPolicy,enforceTrustedX402Endpoint,PaymentPolicyError } from "@/lib/server/payment-policy";
import { isSupportedX402Network } from "@/lib/server/x402-bazaar";
import type { X402Intent,X402PaymentOption,X402Preview,X402RequestMethod } from "@/lib/x402-types";

const PREVIEW_TTL_MS=10*60_000,MAX_REQUEST_BYTES=64_000,MAX_RESPONSE_BYTES=1_000_000,STORED_RESPONSE_CHARS=64_000;
export class X402Error extends Error{constructor(message:string,public readonly code="X402_ERROR"){super(message);this.name="X402Error";}}
export function x402ErrorResponse(error:unknown):Response{const e=error instanceof X402Error?error:error instanceof AgenticWalletError?new X402Error(error.message,error.code):error instanceof PaymentPolicyError?new X402Error(error.message,error.code):new X402Error(error instanceof Error?error.message:"x402 operation failed.");return Response.json({error:e.message,code:e.code},{status:e.code==="X402_EXECUTION_DISABLED"?403:400});}
function allowedHosts(){return(process.env.AGENTPAY_X402_ALLOWED_HOSTS||"").split(",").map(v=>v.trim().toLowerCase()).filter(Boolean);}
export function x402Capability(){return{executionEnabled:process.env.AGENTPAY_ENABLE_X402==="true",allowedHosts:allowedHosts(),supportedNetworks:["eip155:56","eip155:8453","solana:*"],lifecycle:["Prepare","Review","Approve","Pay"]};}
export function validateX402Resource(raw:string):string{let url:URL;try{url=new URL(raw);}catch{throw new X402Error("Enter a valid HTTPS x402 resource URL.","INVALID_X402_URL");}const host=url.hostname.toLowerCase();if(url.protocol!=="https:"||url.username||url.password||url.port||url.hash||host==="localhost"||host.endsWith(".local")||isIP(host)!==0)throw new X402Error("x402 resources must use an allowlisted public HTTPS hostname without credentials, custom ports, or fragments.","INVALID_X402_URL");if(!allowedHosts().includes(host))throw new X402Error("This x402 host is not in the independent server allowlist.","X402_HOST_NOT_ALLOWED");return url.toString();}
function validateMethod(value:unknown):X402RequestMethod{if(value===undefined||value==="GET")return"GET";if(value==="POST")return"POST";throw new X402Error("Only GET and POST x402 resources are supported.","INVALID_X402_METHOD");}
function requestBody(method:X402RequestMethod,value:unknown):string|undefined{if(method==="GET")return;let body:string;try{body=JSON.stringify(value??{});}catch{throw new X402Error("The x402 request body must be valid JSON.","INVALID_X402_BODY");}if(Buffer.byteLength(body)>MAX_REQUEST_BYTES)throw new X402Error("The x402 request body is too large.","X402_REQUEST_TOO_LARGE");return body;}
async function getResource(url:string,method:X402RequestMethod,body?:string,header?:{name:string;value:string}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15_000);try{return await fetch(url,{method,body:method==="POST"?body:undefined,redirect:"error",headers:{Accept:"application/json, text/plain;q=0.9",...(method==="POST"?{"Content-Type":"application/json"}:{}),...(header?{[header.name]:header.value}:{})},signal:controller.signal});}finally{clearTimeout(timer);}}
async function readBoundedResponse(response:Response):Promise<string>{if(!response.body)return"";const reader=response.body.getReader(),chunks:Uint8Array[]=[];let total=0;try{while(true){const {done,value}=await reader.read();if(done)break;if(value){total+=value.byteLength;if(total>MAX_RESPONSE_BYTES)throw new X402Error("Purchased response exceeds the 1 MB safety limit.","X402_RESPONSE_TOO_LARGE");chunks.push(value);}}}finally{reader.releaseLock();}const bytes=new Uint8Array(total);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.byteLength;}return new TextDecoder().decode(bytes);}
function optionNetwork(option:X402PaymentOption):string|undefined{return option.network||(typeof option.originalAccept?.network==="string"?option.originalAccept.network:undefined);}
export function enforceX402OptionPolicy(intent:Pick<X402Intent,"resourceUrl"|"requestMethod">,option:X402PaymentOption):void{const network=optionNetwork(option);if(!network||!isSupportedX402Network(network))throw new X402Error("The selected option is not on a supported x402 v2 network.","X402_NETWORK_NOT_SUPPORTED");try{enforcePaymentPolicy({rail:"x402",amountUsd:option.amountUsd,x402Url:intent.resourceUrl,x402Method:intent.requestMethod});}catch(error){if(error instanceof PaymentPolicyError)throw new X402Error(error.message,error.code);throw error;}}
function applyX402Policy(url:string,method:X402RequestMethod,preview:X402Preview):X402Preview {
 const intent={resourceUrl:url,requestMethod:method};
 const options=preview.options.map(option=>{
  if(option.status!=="READY_TO_SIGN")return option;
  try{enforceX402OptionPolicy(intent,option);return option;}
  catch(error){return {...option,status:"NOT_SIGNABLE" as const,reasons:[...option.reasons,error instanceof Error?error.message:"Policy rejected this option."]};}
 });
 return {...preview,options};
}
export async function prepareX402(input:{url:string;method?:unknown;requestBody?:unknown;source?:X402Intent["source"];catalogResourceId?:string;userRequest?:string}):Promise<X402Intent>{const method=validateMethod(input.method),url=validateX402Resource(input.url);try{enforceTrustedX402Endpoint(url,method);}catch(error){if(error instanceof PaymentPolicyError)throw new X402Error(error.message,error.code);throw error;}const body=requestBody(method,input.requestBody),response=await getResource(url,method,body);if(response.status!==402)throw new X402Error(`Resource returned HTTP ${response.status}, not 402 Payment Required.`,"NOT_X402_RESOURCE");const requirements=response.headers.get("payment-required");if(!requirements||requirements.length>65_536)throw new X402Error("The resource returned no valid PAYMENT-REQUIRED header.","MISSING_PAYMENT_REQUIREMENTS");const preview=await previewX402Payment(requirements);if(!preview.paymentId||!Array.isArray(preview.options))throw new X402Error("Agentic Wallet returned an invalid x402 preview.","INVALID_X402_PREVIEW");const policyPreview=applyX402Policy(url,method,preview);if(!policyPreview.options.some(option=>option.status==="READY_TO_SIGN"))throw new X402Error("No live payment option satisfies the active network, trust, and spending rules.","X402_POLICY_REJECTED");return createX402Intent({url,preview:policyPreview,method,requestBody:body,source:input.source,catalogResourceId:input.catalogResourceId,userRequest:input.userRequest});}
/** Compatibility alias. */ export async function discoverX402(rawUrl:string,method:X402RequestMethod="GET",body?:unknown){return prepareX402({url:rawUrl,method,requestBody:body});}
function ensureFresh(intent:X402Intent){if(Date.now()-Date.parse(intent.createdAt)>PREVIEW_TTL_MS)throw new X402Error("The x402 preview expired. Prepare a fresh payment.","X402_PREVIEW_EXPIRED");}
export function reviewX402(id:string,index:number):X402Intent{const intent=getX402Intent(id);if(intent.status!=="prepared")throw new X402Error("Only a prepared x402 payment can be reviewed.","INVALID_X402_STATUS");ensureFresh(intent);const option=intent.options.find(item=>item.index===index);if(!option||option.status!=="READY_TO_SIGN")throw new X402Error("Select a READY_TO_SIGN payment option.","X402_OPTION_NOT_READY");enforceTrustedX402Endpoint(intent.resourceUrl,intent.requestMethod);enforceX402OptionPolicy(intent,option);return updateX402Intent(id,{status:"reviewed",selectedIndex:index,selectedOption:option,amountUsd:option.amountUsd});}
export function approveX402(id:string):X402Intent{const intent=getX402Intent(id);if(intent.status!=="reviewed"||!intent.selectedOption)throw new X402Error("Review an exact payment option before approving it.","INVALID_X402_STATUS");ensureFresh(intent);enforceTrustedX402Endpoint(intent.resourceUrl,intent.requestMethod);enforceX402OptionPolicy(intent,intent.selectedOption);return updateX402Intent(id,{status:"approved"});}
export function parseX402Receipt(value:string|null):Record<string,unknown>|undefined{if(!value||value.length>65_536)return;try{const parsed=JSON.parse(Buffer.from(value,"base64").toString("utf8"));return parsed&&typeof parsed==="object"&&!Array.isArray(parsed)?parsed as Record<string,unknown>:undefined;}catch{return;}}
export function parseX402SettlementHash(value:string|null):string|undefined{const receipt=parseX402Receipt(value);return typeof receipt?.transaction==="string"&&receipt.transaction?receipt.transaction:typeof receipt?.txHash==="string"&&receipt.txHash?receipt.txHash:undefined;}
function delay(ms:number){return new Promise(resolve=>setTimeout(resolve,ms));}
async function waitForApproval(hash:string,expiresAt:number){const deadline=Math.min(Date.now()+90_000,expiresAt*1000-5_000);while(Date.now()<deadline){const status=await getWalletTransactionStatus(hash);if(status==="confirmed")return;if(status==="failed")throw new X402Error("The Permit2 approval transaction failed.","X402_APPROVAL_FAILED");await delay(2_500);}throw new X402Error("The Permit2 approval did not confirm before the replay deadline. Prepare a fresh payment after it confirms.","X402_APPROVAL_TIMEOUT");}
export async function payX402(id:string):Promise<X402Intent>{const intent=getX402Intent(id);if(intent.status!=="approved"||!intent.selectedOption||!intent.selectedIndex)throw new X402Error("This payment must be reviewed and explicitly approved before Pay.","INVALID_X402_STATUS");if(process.env.AGENTPAY_ENABLE_X402!=="true")throw new X402Error("x402 execution is disabled on this server.","X402_EXECUTION_DISABLED");ensureFresh(intent);enforceTrustedX402Endpoint(intent.resourceUrl,intent.requestMethod);enforceX402OptionPolicy(intent,intent.selectedOption);updateX402Intent(id,{status:"signing"});try{const signature=await signX402Payment(intent.paymentId,intent.selectedIndex);if(signature.paymentHeaderName.toUpperCase()!=="PAYMENT-SIGNATURE"||!signature.paymentHeaderValue||signature.signatureExpiresAt*1000<=Date.now())throw new X402Error("Agentic Wallet returned an invalid or expired payment signature.","INVALID_X402_SIGNATURE");if(signature.approveTxHash){updateX402Intent(id,{status:"approving",approvalTxHash:signature.approveTxHash});await waitForApproval(signature.approveTxHash,signature.signatureExpiresAt);}updateX402Intent(id,{status:"replaying"});const response=await getResource(intent.resourceUrl,intent.requestMethod,intent.requestBody,{name:signature.paymentHeaderName,value:signature.paymentHeaderValue});const declared=Number(response.headers.get("content-length")||0);if(declared>MAX_RESPONSE_BYTES)throw new X402Error("Purchased response exceeds the 1 MB safety limit.","X402_RESPONSE_TOO_LARGE");const raw=await readBoundedResponse(response);const stored=raw.slice(0,STORED_RESPONSE_CHARS),contentType=response.headers.get("content-type")||undefined,kind: "json"|"text"=contentType?.toLowerCase().includes("json")?"json":"text",receipt=parseX402Receipt(response.headers.get("payment-response")),values={responseStatus:response.status,responseContentType:contentType,responseBody:stored,responseKind:kind,resultTruncated:stored.length<raw.length,receipt,settlementTxHash:parseX402SettlementHash(response.headers.get("payment-response"))};if(!response.ok)return updateX402Intent(id,{status:"failed",...values,errorMessage:`Paid request returned HTTP ${response.status}. No retry was attempted.`});return updateX402Intent(id,{status:"completed",...values});}catch(error){updateX402Intent(id,{status:"failed",errorMessage:error instanceof Error?error.message:"x402 payment failed."});throw error;}}
/** Deprecated one-click API intentionally refuses to collapse approval and payment. */
export async function executeX402():Promise<never>{throw new X402Error("One-click x402 execution was removed. Review, approve, and pay through separate steps.","X402_LIFECYCLE_REQUIRED");}
