import { randomUUID } from "node:crypto";
import { mkdirSync } from "node:fs";
import path from "node:path";
import { DatabaseSync } from "node:sqlite";
import type { X402Intent, X402IntentStatus, X402PaymentOption, X402Preview, X402RequestMethod } from "@/lib/x402-types";

type Row=Record<string,unknown>;
let database:DatabaseSync|undefined;let databaseFile="";
function db(){const file=process.env.AGENTPAY_DB_PATH||path.join(process.cwd(),"data","agentpay.sqlite");if(database&&databaseFile===file)return database;database?.close();mkdirSync(path.dirname(file),{recursive:true});database=new DatabaseSync(file);databaseFile=file;database.exec(`CREATE TABLE IF NOT EXISTS x402_intents (
 id TEXT PRIMARY KEY,resource_url TEXT NOT NULL,resource_host TEXT NOT NULL,request_method TEXT NOT NULL DEFAULT 'GET',request_body TEXT,
 source TEXT NOT NULL DEFAULT 'direct',catalog_resource_id TEXT,user_request TEXT,status TEXT NOT NULL,payment_id TEXT NOT NULL,options_json TEXT NOT NULL,
 selected_index INTEGER,selected_option_json TEXT,amount_usd TEXT,reviewed_at TEXT,approved_at TEXT,paid_at TEXT,response_status INTEGER,
 response_content_type TEXT,response_body TEXT,response_kind TEXT,result_truncated INTEGER NOT NULL DEFAULT 0,settlement_tx_hash TEXT,approval_tx_hash TEXT,
 receipt_json TEXT,error_message TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,completed_at TEXT,delivery_status TEXT)`);
 const columns=new Set((database.prepare("PRAGMA table_info(x402_intents)").all() as unknown as Array<{name:string}>).map(c=>c.name));
 const additions:Record<string,string>={request_method:"TEXT NOT NULL DEFAULT 'GET'",request_body:"TEXT",source:"TEXT NOT NULL DEFAULT 'direct'",catalog_resource_id:"TEXT",user_request:"TEXT",selected_option_json:"TEXT",amount_usd:"TEXT",reviewed_at:"TEXT",approved_at:"TEXT",paid_at:"TEXT",response_kind:"TEXT",result_truncated:"INTEGER NOT NULL DEFAULT 0",receipt_json:"TEXT",approval_tx_hash:"TEXT",delivery_status:"TEXT"};
 for(const [name,type] of Object.entries(additions))if(!columns.has(name))database.exec(`ALTER TABLE x402_intents ADD COLUMN ${name} ${type}`);
 database.exec("UPDATE x402_intents SET status='prepared' WHERE status='awaiting-approval'");return database;}
function optional(row:Row,key:string):string|undefined{return row[key]===null||row[key]===undefined?undefined:String(row[key]);}
function parsed<T>(value:unknown):T|undefined{if(typeof value!=="string")return;try{return JSON.parse(value) as T;}catch{return;}}
function map(row:Row):X402Intent{const options=parsed<X402PaymentOption[]>(row.options_json)||[],selectedIndex=row.selected_index===null||row.selected_index===undefined?undefined:Number(row.selected_index);return {id:String(row.id),resourceUrl:String(row.resource_url),resourceHost:String(row.resource_host),requestMethod:(row.request_method||"GET") as X402RequestMethod,requestBody:optional(row,"request_body"),source:(row.source||"direct") as X402Intent["source"],catalogResourceId:optional(row,"catalog_resource_id"),userRequest:optional(row,"user_request"),status:String(row.status) as X402IntentStatus,paymentId:String(row.payment_id),options,selectedIndex,selectedOption:parsed(row.selected_option_json)??options.find(v=>v.index===selectedIndex),amountUsd:optional(row,"amount_usd"),reviewedAt:optional(row,"reviewed_at"),approvedAt:optional(row,"approved_at"),paidAt:optional(row,"paid_at"),responseStatus:row.response_status===null||row.response_status===undefined?undefined:Number(row.response_status),responseContentType:optional(row,"response_content_type"),responseBody:optional(row,"response_body"),responseKind:optional(row,"response_kind") as X402Intent["responseKind"],resultTruncated:Boolean(row.result_truncated),settlementTxHash:optional(row,"settlement_tx_hash"),approvalTxHash:optional(row,"approval_tx_hash"),receipt:parsed(row.receipt_json),errorMessage:optional(row,"error_message"),createdAt:String(row.created_at),updatedAt:String(row.updated_at),completedAt:optional(row,"completed_at"),deliveryStatus:optional(row,"delivery_status") as X402Intent["deliveryStatus"]};}
export function createX402Intent(input:{url:string;preview:X402Preview;method?:X402RequestMethod;requestBody?:string;source?:X402Intent["source"];catalogResourceId?:string;userRequest?:string}):X402Intent{const now=new Date().toISOString(),id=randomUUID(),method=input.method||"GET";db().prepare(`INSERT INTO x402_intents(id,resource_url,resource_host,request_method,request_body,source,catalog_resource_id,user_request,status,payment_id,options_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,input.url,new URL(input.url).hostname.toLowerCase(),method,input.requestBody??null,input.source||"direct",input.catalogResourceId??null,input.userRequest?.slice(0,1000)??null,"prepared",input.preview.paymentId,JSON.stringify(input.preview.options),now,now);return getX402Intent(id);}
export function getX402Intent(id:string):X402Intent{const row=db().prepare("SELECT * FROM x402_intents WHERE id=?").get(id) as Row|undefined;if(!row)throw new Error("x402 intent not found.");return map(row);}
type Update=Partial<Pick<X402Intent,"status"|"selectedIndex"|"selectedOption"|"amountUsd"|"responseStatus"|"responseContentType"|"responseBody"|"responseKind"|"resultTruncated"|"settlementTxHash"|"approvalTxHash"|"receipt"|"errorMessage"|"deliveryStatus">>;
export function updateX402Intent(id:string,values:Update):X402Intent{const current=getX402Intent(id),status=values.status??current.status,now=new Date().toISOString(),selected=values.selectedOption??current.selectedOption;const reviewedAt=status==="reviewed"&&!current.reviewedAt?now:current.reviewedAt,approvedAt=status==="approved"&&!current.approvedAt?now:current.approvedAt,paidAt=["signing","approving","replaying","completed","failed"].includes(status)&&current.approvedAt&&!current.paidAt?now:current.paidAt,completedAt=["completed","cancelled","failed"].includes(status)?current.completedAt||now:current.completedAt;db().prepare(`UPDATE x402_intents SET status=?,selected_index=?,selected_option_json=?,amount_usd=?,reviewed_at=?,approved_at=?,paid_at=?,response_status=?,response_content_type=?,response_body=?,response_kind=?,result_truncated=?,settlement_tx_hash=?,approval_tx_hash=?,receipt_json=?,error_message=?,updated_at=?,completed_at=?,delivery_status=? WHERE id=?`).run(status,values.selectedIndex??current.selectedIndex??null,selected?JSON.stringify(selected):null,values.amountUsd??current.amountUsd??null,reviewedAt??null,approvedAt??null,paidAt??null,values.responseStatus??current.responseStatus??null,values.responseContentType??current.responseContentType??null,values.responseBody??current.responseBody??null,values.responseKind??current.responseKind??null,Number(values.resultTruncated??current.resultTruncated),values.settlementTxHash??current.settlementTxHash??null,values.approvalTxHash??current.approvalTxHash??null,JSON.stringify(values.receipt??current.receipt??null),values.errorMessage??current.errorMessage??null,now,completedAt??null,values.deliveryStatus??current.deliveryStatus??null,id);return getX402Intent(id);}
export function cancelX402Intent(id:string):X402Intent{const intent=getX402Intent(id);if(["completed","failed","cancelled","signing","approving","replaying"].includes(intent.status))throw new Error("This x402 intent can no longer be cancelled.");return updateX402Intent(id,{status:"cancelled",deliveryStatus:"cancelled",errorMessage:"Cancelled before payment."});}
export function listX402Intents():X402Intent[]{return (db().prepare("SELECT * FROM x402_intents ORDER BY updated_at DESC LIMIT 100").all() as Row[]).map(map);}
export function resetX402StoreForTests(){database?.close();database=undefined;databaseFile="";}
