import { randomUUID } from "node:crypto";
import { mkdirSync } from "node:fs";
import path from "node:path";
import { DatabaseSync } from "node:sqlite";
import type { X402Intent, X402IntentStatus, X402Preview } from "@/lib/x402-types";

interface Row { id:string; resource_url:string; resource_host:string; request_method:"GET"|"POST"; request_body:string|null; status:X402IntentStatus; payment_id:string; options_json:string; selected_index:number|null; response_status:number|null; response_content_type:string|null; response_body:string|null; settlement_tx_hash:string|null; approval_tx_hash:string|null; error_message:string|null; created_at:string; updated_at:string; completed_at:string|null }
let database: DatabaseSync | undefined;
function db() { if (database) return database; const file=process.env.AGENTPAY_DB_PATH||path.join(process.cwd(),"data","agentpay.sqlite"); mkdirSync(path.dirname(file),{recursive:true}); database=new DatabaseSync(file); database.exec(`CREATE TABLE IF NOT EXISTS x402_intents (id TEXT PRIMARY KEY,resource_url TEXT NOT NULL,resource_host TEXT NOT NULL,request_method TEXT NOT NULL DEFAULT 'GET',request_body TEXT,status TEXT NOT NULL,payment_id TEXT NOT NULL,options_json TEXT NOT NULL,selected_index INTEGER,response_status INTEGER,response_content_type TEXT,response_body TEXT,settlement_tx_hash TEXT,approval_tx_hash TEXT,error_message TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,completed_at TEXT)`); const columns=(database.prepare("PRAGMA table_info(x402_intents)").all() as unknown as Array<{name:string}>).map(column=>column.name); if(!columns.includes("approval_tx_hash"))database.exec("ALTER TABLE x402_intents ADD COLUMN approval_tx_hash TEXT"); if(!columns.includes("request_method"))database.exec("ALTER TABLE x402_intents ADD COLUMN request_method TEXT NOT NULL DEFAULT 'GET'"); if(!columns.includes("request_body"))database.exec("ALTER TABLE x402_intents ADD COLUMN request_body TEXT"); return database; }
function map(row: Row): X402Intent { return {id:row.id,resourceUrl:row.resource_url,resourceHost:row.resource_host,requestMethod:row.request_method||"GET",requestBody:row.request_body??undefined,status:row.status,paymentId:row.payment_id,options:JSON.parse(row.options_json),selectedIndex:row.selected_index??undefined,responseStatus:row.response_status??undefined,responseContentType:row.response_content_type??undefined,responseBody:row.response_body??undefined,settlementTxHash:row.settlement_tx_hash??undefined,approvalTxHash:row.approval_tx_hash??undefined,errorMessage:row.error_message??undefined,createdAt:row.created_at,updatedAt:row.updated_at,completedAt:row.completed_at??undefined}; }
export function createX402Intent(url:string, preview:X402Preview, method:"GET"|"POST"="GET", requestBody?:string):X402Intent { const now=new Date().toISOString(), id=randomUUID(), host=new URL(url).hostname; db().prepare(`INSERT INTO x402_intents(id,resource_url,resource_host,request_method,request_body,status,payment_id,options_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(id,url,host,method,requestBody??null,"awaiting-approval",preview.paymentId,JSON.stringify(preview.options),now,now); return getX402Intent(id); }
export function getX402Intent(id:string):X402Intent { const row=db().prepare("SELECT * FROM x402_intents WHERE id=?").get(id) as unknown as Row|undefined; if(!row) throw new Error("x402 intent not found."); return map(row); }
export function updateX402Intent(id:string, values:{status:X402IntentStatus;selectedIndex?:number;responseStatus?:number;responseContentType?:string;responseBody?:string;settlementTxHash?:string;approvalTxHash?:string;errorMessage?:string}):X402Intent { const now=new Date().toISOString(), done=values.status==="completed"||values.status==="failed"?now:null; db().prepare(`UPDATE x402_intents SET status=?,selected_index=COALESCE(?,selected_index),response_status=COALESCE(?,response_status),response_content_type=COALESCE(?,response_content_type),response_body=COALESCE(?,response_body),settlement_tx_hash=COALESCE(?,settlement_tx_hash),approval_tx_hash=COALESCE(?,approval_tx_hash),error_message=COALESCE(?,error_message),updated_at=?,completed_at=COALESCE(?,completed_at) WHERE id=?`).run(values.status,values.selectedIndex??null,values.responseStatus??null,values.responseContentType??null,values.responseBody??null,values.settlementTxHash??null,values.approvalTxHash??null,values.errorMessage??null,now,done,id); return getX402Intent(id); }
export function listX402Intents():X402Intent[]{ return (db().prepare("SELECT * FROM x402_intents ORDER BY updated_at DESC LIMIT 100").all() as unknown as Row[]).map(map); }
