"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { BalanceSnapshot } from "@/lib/balance-snapshot-types";

type Event={id:string;source:string;activityType:string;status:string;statusGroup:string;statusCategory:string;amount?:string;asset?:string;title:string;summary:string;occurredAt:string;createdAt:string;updatedAt:string;reference?:string};
type Page={events:Event[];pagination:{page:number;limit:number;total:number;totalPages:number;hasNextPage:boolean;hasPreviousPage:boolean}};
const empty:Page={events:[],pagination:{page:1,limit:25,total:0,totalPages:0,hasNextPage:false,hasPreviousPage:false}};

export function ActivityWorkflow(){
  const[data,setData]=useState<Page>(empty),[snapshots,setSnapshots]=useState<BalanceSnapshot[]>([]);
  const[status,setStatus]=useState(""),[source,setSource]=useState(""),[activityType,setActivityType]=useState(""),[asset,setAsset]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[search,setSearch]=useState(""),[sort,setSort]=useState("newest");
  const[page,setPage]=useState(1),[loading,setLoading]=useState(true),[capturing,setCapturing]=useState(false),[error,setError]=useState(""),[selected,setSelected]=useState<Event|null>(null);
  const query=useMemo(()=>{const q=new URLSearchParams({page:String(page),limit:"25",sort});if(status)q.set("statusGroup",status);if(source)q.set("source",source);if(activityType)q.set("activityType",activityType);if(asset.trim())q.set("asset",asset.trim());if(from)q.set("from",from);if(to)q.set("to",to);if(search.trim())q.set("search",search.trim());return q},[activityType,asset,from,page,search,sort,source,status,to]);
  const exportQuery=useMemo(()=>{const q=new URLSearchParams(query);q.delete("page");q.delete("limit");return q},[query]);
  const loadSnapshots=useCallback(async()=>{try{const r=await fetch("/api/payments/activity/snapshots",{cache:"no-store"});if(r.ok)setSnapshots((await r.json()).snapshots||[])}catch{/* activity remains usable */}},[]);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await fetch(`/api/payments/activity?${query}`,{cache:"no-store"});const x=await r.json();if(!r.ok)throw new Error(x.error||"Unable to load activity.");setData({events:x.events||[],pagination:x.pagination||empty.pagination});}catch(e){setError(e instanceof Error?e.message:"Unable to load activity.");}finally{setLoading(false)}},[query]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),search?250:0);return()=>window.clearTimeout(timer)},[load,search]);
  useEffect(()=>{void loadSnapshots()},[loadSnapshots]);
  function change(setter:(v:string)=>void,value:string){setter(value);setPage(1)}
  async function capture(){setCapturing(true);setError("");try{const r=await fetch("/api/payments/activity/snapshots",{method:"POST"});const x=await r.json();if(!r.ok)throw new Error(x.error||"Unable to capture balances.");await Promise.all([loadSnapshots(),load()]);}catch(e){setError(e instanceof Error?e.message:"Unable to capture balances.");}finally{setCapturing(false)}}
  return <div className="activity-workspace">
    <div className="activity-actions"><div><strong>Balance snapshots</strong><span>{snapshots.length?"Recent captures are stored locally for later history and reporting.":"Capture current balances without enabling payment execution."}</span></div><div><a className="secondary-button link-button" href={`/api/payments/activity/export?${exportQuery}`} download>Export filtered CSV</a><button className="primary-button" disabled={capturing} onClick={()=>void capture()}>{capturing?"Capturing…":"Capture balances"}</button></div></div>
    {snapshots.length>0&&<div className="snapshot-summary" aria-label="Recent balance snapshots">{snapshots.slice(0,4).map(item=><div key={item.id}><strong>{sourceLabel(item.source)}</strong><span className={`snapshot-state ${item.status}`}>{item.status}</span><small>{item.status==="captured"?`${item.assetCount} assets · ${item.totalUsd===null?"USD value unavailable":formatUsd(item.totalUsd)}`:item.message}</small><time>{new Date(item.capturedAt).toLocaleString()}</time></div>)}</div>}
    <div className="activity-toolbar">
      <label className="activity-search"><span>⌕</span><input aria-label="Search activity" value={search} onChange={e=>change(setSearch,e.target.value)} placeholder="Search activity"/></label>
      <select aria-label="Filter by status" value={status} onChange={e=>change(setStatus,e.target.value)}><option value="">All statuses</option><option value="awaiting-approval">Awaiting approval</option><option value="in-progress">Pending</option><option value="successful">Successful</option><option value="failed">Failed</option></select>
      <select aria-label="Filter by source" value={source} onChange={e=>change(setSource,e.target.value)}><option value="">All sources</option><option value="agentic-wallet">Agentic Wallet</option><option value="binance-pay">Binance Pay</option><option value="binance-account">Binance Account</option><option value="x402">x402</option></select>
      <select aria-label="Filter by activity type" value={activityType} onChange={e=>change(setActivityType,e.target.value)}><option value="">All types</option><option value="transfer">Transfer</option><option value="binance-pay">Binance Pay</option><option value="x402">x402</option><option value="balance-snapshot">Balance snapshot</option><option value="policy-rejection">Policy rejection</option></select>
      <label className="activity-filter"><span>Asset</span><input value={asset} maxLength={20} onChange={e=>change(setAsset,e.target.value)} placeholder="USDT"/></label>
      <label className="activity-filter"><span>From</span><input type="date" value={from} onChange={e=>change(setFrom,e.target.value)}/></label>
      <label className="activity-filter"><span>To</span><input type="date" value={to} onChange={e=>change(setTo,e.target.value)}/></label>
      <select aria-label="Sort activity" value={sort} onChange={e=>change(setSort,e.target.value)}><option value="newest">Newest first</option><option value="oldest">Oldest first</option></select>
    </div>
    {error&&<div className="workflow-error">{error}</div>}
    {loading?<div className="workflow-message">Loading activity…</div>:!data.events.length?<div className="empty-state"><div className="empty-icon">◷</div><h2>No matching activity</h2><p>Change or clear the filters to see other approvals, payments, purchases, and snapshots.</p></div>:<div className="activity-table"><div className="activity-table-head"><span>Activity</span><span>Source</span><span>Status</span><span>Time</span></div>{data.events.map(event=><button type="button" className="activity-table-row" key={event.id} onClick={()=>setSelected(event)} aria-label={`View details for ${event.title}`}><span><strong>{event.title}</strong><small>{event.summary}{event.reference?` · ${event.reference}`:""}</small></span><span className="source-chip">{sourceLabel(event.source)}</span><span className={`review-status ${event.statusCategory} ${event.statusGroup}`}>{event.statusGroup.replaceAll("-"," ")}</span><time>{new Date(event.occurredAt).toLocaleString()}</time></button>)}</div>}
    <div className="activity-pagination"><span>{data.pagination.total} activities · Page {data.pagination.page} of {Math.max(1,data.pagination.totalPages)}</span><div><button className="secondary-button" disabled={!data.pagination.hasPreviousPage||loading} onClick={()=>setPage(p=>p-1)}>Previous</button><button className="secondary-button" disabled={!data.pagination.hasNextPage||loading} onClick={()=>setPage(p=>p+1)}>Next</button></div></div>
    {selected&&<ActivityDetail event={selected} onClose={()=>setSelected(null)}/>}  </div>
}
function ActivityDetail({event,onClose}:{event:Event;onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const dialog=ref.current;if(dialog&&!dialog.open)dialog.showModal();return()=>{if(dialog?.open)dialog.close()}},[]);return <dialog ref={ref} className="activity-detail" aria-labelledby="activity-detail-title" onClose={onClose} onCancel={event=>{event.preventDefault();onClose()}}><div className="activity-detail-heading"><div><span>Normalized event</span><h2 id="activity-detail-title">{event.title}</h2></div><button className="ghost-button" aria-label="Close event details" onClick={onClose}>Close</button></div><dl><Detail label="Type" value={event.activityType}/><Detail label="Source" value={sourceLabel(event.source)}/><Detail label="Status" value={event.status}/>{event.amount&&<Detail label="Amount" value={`${event.amount}${event.asset?` ${event.asset}`:""}`}/>}<Detail label="Summary" value={event.summary}/>{event.reference&&<Detail label="Reference" value={event.reference}/>}<Detail label="Occurred" value={new Date(event.occurredAt).toLocaleString()}/><Detail label="Created" value={new Date(event.createdAt).toLocaleString()}/><Detail label="Updated" value={new Date(event.updatedAt).toLocaleString()}/></dl></dialog>}
function Detail({label,value}:{label:string;value:string}){return <div><dt>{label}</dt><dd>{value}</dd></div>}
function sourceLabel(source:string){return source.replace("agentic-wallet","Agentic Wallet").replace("binance-pay","Binance Pay").replace("binance-account","Binance Account")}
function formatUsd(value:number){return value.toLocaleString(undefined,{style:"currency",currency:"USD",maximumFractionDigits:2})}
