"use client";
import { useEffect, useState } from "react";
import type { X402Intent } from "@/lib/x402-types";

export function X402Workflow(){
 const [url,setUrl]=useState(""); const [intent,setIntent]=useState<X402Intent|null>(null); const [enabled,setEnabled]=useState(false); const [hosts,setHosts]=useState<string[]>([]); const [error,setError]=useState(""); const [working,setWorking]=useState(false);
 useEffect(()=>{void fetch("/api/x402/status",{cache:"no-store"}).then(r=>r.json()).then(x=>{setEnabled(x.executionEnabled===true);setHosts(x.allowedHosts||[]);});},[]);
 async function discover(){setWorking(true);setError("");setIntent(null);try{const r=await fetch("/api/x402/discover",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url})});const x=await r.json();if(!r.ok)throw new Error(x.error||"Unable to inspect x402 resource.");setIntent(x);}catch(e){setError(e instanceof Error?e.message:"Unable to inspect x402 resource.");}finally{setWorking(false);}}
 async function execute(index:number){if(!intent)return;setWorking(true);setError("");try{const r=await fetch("/api/x402/execute",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:intent.id,selectedIndex:index})});const x=await r.json();if(!r.ok)throw new Error(x.error||"Unable to execute x402 payment.");setIntent(x);}catch(e){setError(e instanceof Error?e.message:"Unable to execute x402 payment.");}finally{setWorking(false);}}
 return <div className="binance-pay-workflow"><div className="notice"><span>402</span><div><strong>Allowed x402 hosts</strong><p>{hosts.length?hosts.join(", "):"No hosts configured. Add trusted merchant hosts server-side before inspection."}</p></div></div><label className="field full"><span>x402 HTTPS resource</span><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://trusted-service.example/api/resource" /></label><button className="primary-button workflow-submit" disabled={working||!url||!hosts.length} onClick={()=>void discover()}>{working?"Inspecting…":"Inspect payment requirement"}</button>{error&&<div className="workflow-error">{error}</div>}{intent&&<div className="x402-options"><h2>Payment options from {intent.resourceHost}</h2>{intent.options.map(option=><article className="x402-option" key={option.index}><div><span className={`review-status ${option.status.toLowerCase()}`}>{option.status.replaceAll("_"," ")}</span><strong>{option.amount} {option.tokenSymbol}</strong><small>{option.binanceChainId} · {option.assetTransferMethod} · ${option.amountUsd??"—"}</small><code>{option.payTo}</code>{option.reasons.length>0&&<p>{option.reasons.join(", ")}</p>}</div>{option.status==="READY_TO_SIGN"&&!option.needApproveFirst&&(enabled?<button className="primary-button" disabled={working} onClick={()=>void execute(option.index)}>Approve and pay</button>:<span className="approved-note">Execution disabled</span>)}</article>)}{intent.status==="completed"&&<div className="binance-pay-success"><h2>Resource purchased</h2><pre>{intent.responseBody}</pre></div>}</div>}</div>;
}
